// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AtomCalendar: typeof import('@atom/atom-ui/es')['Calendar']
    AtomCalendarTab: typeof import('@atom/atom-ui/es')['CalendarTab']
    AtomCard: typeof import('@atom/atom-ui/es')['Card']
    AtomClamp: typeof import('@atom/atom-ui/es')['Clamp']
    AtomEmpty: typeof import('@atom/atom-ui/es')['Empty']
    AtomIcon: typeof import('@atom/atom-ui/es')['Icon']
    AtomLoading: typeof import('@atom/atom-ui/es')['Loading']
    AtomSticky: typeof import('@atom/atom-ui/es')['Sticky']
    AtomSwipe: typeof import('@atom/atom-ui/es')['Swipe']
    AtomSwipeItem: typeof import('@atom/atom-ui/es')['SwipeItem']
    AtomTab: typeof import('@atom/atom-ui/es')['Tab']
    AtomTabs: typeof import('@atom/atom-ui/es')['Tabs']
    BoardCard: typeof import('./../components/common/BoardCard.vue')['default']
    CalendarRange: typeof import('./../components/featured-quotes/calendar-range/index.vue')['default']
    DarkBoard: typeof import('./../components/featured-quotes/dark-board/index.vue')['default']
    FundFlow: typeof import('./../components/featured-quotes/market-temp/FundFlow.vue')['default']
    HeaderNav: typeof import('./../components/common/HeaderNav.vue')['default']
    MarketTemp: typeof import('./../components/featured-quotes/market-temp/index.vue')['default']
    PageStatus: typeof import('./../components/common/PageStatus/PageStatus.vue')['default']
    RankItem: typeof import('./../components/common/RankItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectorList: typeof import('./../components/featured-quotes/dark-board/SectorList.vue')['default']
    StockList: typeof import('./../components/featured-quotes/dark-board/StockList.vue')['default']
    VanEmpty: typeof import('vant/es')['Empty']
    VanLoading: typeof import('vant/es')['Loading']
  }
}
